name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  base:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        image:
          - dir: base
            name: base:latest
            tag: base

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build ${{ matrix.image.name }}
      run: |
        docker pull ghcr.io/snakepacker/python/${{ matrix.image.name }} || true
        docker build -t ghcr.io/snakepacker/python/${{ matrix.image.name }} ${{ matrix.image.dir }}
        docker tag ghcr.io/snakepacker/python/${{ matrix.image.name }} snakepacker/python:${{ matrix.image.tag }}

    - name: Pushing to ghcr.io ${{ matrix.image.name }}
      run: docker push ghcr.io/snakepacker/python/${{ matrix.image.name }}

  images:
    needs: base
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        image:

          - dir: all
            name: all:latest
            tag: all

          - dir: python2.7
            name: 2.7:latest
            tag: 2.7

          - dir: python3.5
            name: 3.5:latest
            tag: 3.5

          - dir: python3.6
            name: 3.6:latest
            tag: 3.6

          - dir: python3.7
            name: 3.7:latest
            tag: 3.7

          - dir: python3.8
            name: 3.8:latest
            tag: 3.8

          - dir: python3.9
            name: 3.9:latest
            tag: 3.9

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build ${{ matrix.image.name }}
      run: |
        docker pull ghcr.io/snakepacker/python/${{ matrix.image.name }} || true
        docker build -t ghcr.io/snakepacker/python/${{ matrix.image.name }} ${{ matrix.image.dir }}
        docker tag ghcr.io/snakepacker/python/${{ matrix.image.name }} snakepacker/python:${{ matrix.image.tag }}

    - name: Pushing to ghcr.io ${{ matrix.image.name }}
      run: docker push ghcr.io/snakepacker/python/${{ matrix.image.name }}

  images-pillow:
    needs: images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        image:
          - dir: pillow/2.7
            name: 2.7:pillow
            tag: 2.7-pillow

          - dir: pillow/3.5
            name: 3.5:pillow
            tag: 3.5-pillow

          - dir: pillow/3.6
            name: 3.6:pillow
            tag: 3.6-pillow

          - dir: pillow/3.7
            name: 3.7:pillow
            tag: 3.7-pillow

          - dir: pillow/3.8
            name: 3.8:pillow
            tag: 3.8-pillow

          - dir: pillow/3.9
            name: 3.9:pillow
            tag: 3.9-pillow

          - dir: pillow/all
            name: all:pillow
            tag: all-pillow

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build ${{ matrix.image.name }}
      run: |
        docker pull ghcr.io/snakepacker/python/${{ matrix.image.name }} || true
        docker build -t ghcr.io/snakepacker/python/${{ matrix.image.name }} ${{ matrix.image.dir }}
        docker tag ghcr.io/snakepacker/python/${{ matrix.image.name }} snakepacker/python:${{ matrix.image.tag }}

    - name: Pushing to ghcr.io ${{ matrix.image.name }}
      run: docker push ghcr.io/snakepacker/python/${{ matrix.image.name }}


  apps:
    needs: images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        image:

          - dir: ipython
            name: ipython:latest
            tag: ipython

          - dir: pylama
            name: pylama:latest
            tag: pylama

          - dir: pylava
            name: pylava:latest
            tag: pylava

          - dir: certbot
            name: certbot:latest
            tag: certbot

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build ${{ matrix.image.name }}
      run: |
        docker pull ghcr.io/snakepacker/python/${{ matrix.image.name }} || true
        docker build -t ghcr.io/snakepacker/python/${{ matrix.image.name }} ${{ matrix.image.dir }}
        docker tag ghcr.io/snakepacker/python/${{ matrix.image.name }} snakepacker/python:${{ matrix.image.tag }}

    - name: Pushing to ghcr.io ${{ matrix.image.name }}
      run: docker push ghcr.io/snakepacker/python/${{ matrix.image.name }}

  push:
    needs: apps
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to hub.docker.io Container Registry
        uses: docker/login-action@v1
        with:
          username: mosquito
          password: ${{ secrets.DH_TOKEN }}

      - name: Push images
        run: |
          docker push ghcr.io/snakepacker/python/base
          docker push ghcr.io/snakepacker/python/all
          docker push ghcr.io/snakepacker/python/all:pillow
          docker push ghcr.io/snakepacker/python/2.7
          docker push ghcr.io/snakepacker/python/3.5
          docker push ghcr.io/snakepacker/python/3.6
          docker push ghcr.io/snakepacker/python/3.7
          docker push ghcr.io/snakepacker/python/3.8
          docker push ghcr.io/snakepacker/python/3.9
          docker push ghcr.io/snakepacker/python/2.7:pillow
          docker push ghcr.io/snakepacker/python/3.5:pillow
          docker push ghcr.io/snakepacker/python/3.6:pillow
          docker push ghcr.io/snakepacker/python/3.7:pillow
          docker push ghcr.io/snakepacker/python/3.8:pillow
          docker push ghcr.io/snakepacker/python/3.9:pillow
          docker push ghcr.io/snakepacker/python/ipython
          docker push ghcr.io/snakepacker/python/pylava
          docker push ghcr.io/snakepacker/python/pylama
          docker push ghcr.io/snakepacker/python/certbot
          docker push snakepacker/python:all
          docker push snakepacker/python:all-pillow
          docker push snakepacker/python:2.7
          docker push snakepacker/python:3.5
          docker push snakepacker/python:3.6
          docker push snakepacker/python:3.7
          docker push snakepacker/python:3.8
          docker push snakepacker/python:3.9
          docker push snakepacker/python:2.7-pillow
          docker push snakepacker/python:3.5-pillow
          docker push snakepacker/python:3.6-pillow
          docker push snakepacker/python:3.7-pillow
          docker push snakepacker/python:3.8-pillow
          docker push snakepacker/python:3.9-pillow
          docker push snakepacker/python:ipython
          docker push snakepacker/python:pylava
          docker push snakepacker/python:pylama
          docker push snakepacker/python:certbot
